name: Build

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:


jobs:
  build:
    name: Gradle-Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      # Setup JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: 'zulu'
          cache: 'gradle'
        
      # Build
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build with Gradle
        run: ./gradlew build

      # Auto release
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts  
          path: |  
            eco-core/core-stub/build/libs/core-stub-*.jar
            eco-core/core-plugin/build/libs/core-plugin-*.jar
            eco-core/core-proxy/build/libs/core-proxy-*.jar
            bin/*.jar
            LICENSE
